function Tc = ControlTorque2(I1,I2,d1,d2,g,kd,kp,l1,m1,m2,th1,th2,th2d,thdot1,thdot2)
%CONTROLTORQUE2
%    TC = CONTROLTORQUE2(I1,I2,D1,D2,G,KD,KP,L1,M1,M2,TH1,TH2,TH2D,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Jun-2016 17:45:20

t2 = d2.^2;
t3 = m2.*t2;
t5 = cos(th2);
t9 = d2.*l1.*m2.*t5;
t4 = I2+t3+t9;
t6 = cos(th1);
t7 = th1+th2;
t8 = cos(t7);
t10 = d1.^2;
t11 = m1.*t10;
t12 = l1.^2;
t13 = m2.*t12;
t14 = d2.*l1.*m2.*t5.*2.0;
t15 = I1+I2+t3+t11+t13+t14;
t16 = 1.0./t15;
t17 = sin(th2);
Tc = -(kd.*thdot2+kp.*(th2-th2d)).*(I2+t3-t4.^2.*t16)-g.*t4.*t16.*(d1.*m1.*t6+d2.*m2.*t8+l1.*m2.*t6)+d2.*g.*m2.*t8+d2.*l1.*m2.*t17.*thdot1.^2+d2.*l1.*m2.*t4.*t16.*t17.*thdot2.*(thdot1.*2.0+thdot2);
