function Tc = ControlTorque1(I1,I2,d1,d2,g,kd,kp,l1,m1,m2,th1,th2,th1d,thdot1,thdot2)
%CONTROLTORQUE1
%    TC = CONTROLTORQUE1(I1,I2,D1,D2,G,KD,KP,L1,M1,M2,TH1,TH2,TH1D,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Jun-2016 17:45:19

t2 = d2.^2;
t3 = m2.*t2;
t4 = cos(th2);
t5 = d2.*l1.*m2.*t4;
t6 = I2+t3;
t7 = cos(th1);
t8 = th1+th2;
t9 = cos(t8);
t10 = I2+t3+t5;
t11 = 1.0./t10;
t12 = sin(th2);
Tc = -(kd.*thdot1+kp.*(th1-th1d)).*(I2+t3+t5-t6.*t11.*(I1+I2+t3+d1.^2.*m1+l1.^2.*m2+d2.*l1.*m2.*t4.*2.0))-g.*t6.*t11.*(d1.*m1.*t7+d2.*m2.*t9+l1.*m2.*t7)+d2.*g.*m2.*t9+d2.*l1.*m2.*t12.*thdot1.^2+d2.*l1.*m2.*t6.*t11.*t12.*thdot2.*(thdot1.*2.0+thdot2);
