function eqn2 = Thdotdot2(I1,I2,T1,T2,d1,d2,g,l1,m1,m2,th1,th2,thdot1,thdot2)
%THDOTDOT2
%    EQN2 = THDOTDOT2(I1,I2,T1,T2,D1,D2,G,L1,M1,M2,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Jun-2016 17:45:18

t2 = d2.^2;
t3 = l1.^2;
t4 = d1.^2;
t5 = m2.^2;
t6 = thdot1.^2;
t7 = sin(th2);
t8 = th1+th2;
t9 = cos(t8);
t10 = cos(th1);
t11 = cos(th2);
t12 = th2.*2.0;
t13 = thdot2.^2;
t14 = sin(t12);
t15 = th1-th2;
t16 = cos(t15);
eqn2 = -(I1.*T2.*-2.0+I2.*T1.*2.0-I2.*T2.*2.0+T1.*m2.*t2.*2.0-T2.*m2.*t2.*2.0-T2.*m1.*t4.*2.0-T2.*m2.*t3.*2.0+I1.*d2.*g.*m2.*t9.*2.0-I2.*d1.*g.*m1.*t10.*2.0-I2.*g.*l1.*m2.*t10.*2.0+T1.*d2.*l1.*m2.*t11.*2.0-T2.*d2.*l1.*m2.*t11.*4.0+d2.*g.*t3.*t5.*t9-d2.*g.*t3.*t5.*t16-g.*l1.*t2.*t5.*t10+t2.*t3.*t5.*t6.*t14.*2.0+t2.*t3.*t5.*t13.*t14+g.*l1.*t2.*t5.*cos(t12+th1)+t2.*t3.*t5.*t14.*thdot1.*thdot2.*2.0+I1.*d2.*l1.*m2.*t6.*t7.*2.0+I2.*d2.*l1.*m2.*t6.*t7.*2.0+I2.*d2.*l1.*m2.*t7.*t13.*2.0-d1.*g.*m1.*m2.*t2.*t10.*2.0+d2.*g.*m1.*m2.*t4.*t9.*2.0+d2.*l1.*t2.*t5.*t6.*t7.*2.0+d2.*l1.*t3.*t5.*t6.*t7.*2.0+d2.*l1.*t2.*t5.*t7.*t13.*2.0+I2.*d2.*l1.*m2.*t7.*thdot1.*thdot2.*4.0-d1.*d2.*g.*l1.*m1.*m2.*t9-d1.*d2.*g.*l1.*m1.*m2.*t16+d2.*l1.*m1.*m2.*t4.*t6.*t7.*2.0+d2.*l1.*t2.*t5.*t7.*thdot1.*thdot2.*4.0)./(I1.*I2.*2.0+I1.*m2.*t2.*2.0+I2.*m1.*t4.*2.0+I2.*m2.*t3.*2.0+t2.*t3.*t5+m1.*m2.*t2.*t4.*2.0-t2.*t3.*t5.*cos(t12));
